### DISCUSSION TITLE
Is there a way to run this action across all repositories in an organization?

### DISCUSSION THREAD

**Discussion by andrewwise** [actions/stale#1089] [Q&A]
Is there a way to run this action across all repositories in an organization? Obviously it can be applied per repository one by one, but is there a better way?

Thanks in advance!

**Comment by ReenigneArcher** [comment]
I'm also interested in this as it would be much easier to only put the workflow in a single repo, and run it as a matrix.

The issue being is that there does not need seem to be a repository input field, so it seems to only use the context of the repository where it's running from... and I don't know if it's possible to overwrite the github context (I doubt it is)...

**Reply by andrewwise** [reply]
I did get an alternative working with [austenstone/get-org-repos](https://github.com/austenstone/get-org-repos) and a forked version Stale  ([amenocal/stale](https://github.com/amenocal/stale) from PR #1081) using a [Job matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).

It has a maximum of 256 repositories it can process this way.

Here is my workflow file, if it's of any use:

```yml
name: Stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
        id: get-org-repos
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}

  sync:
    needs:
      - get-org-repos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@main
        with:
          repository: ${{ github.event.organization.login }}/${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN }}
      - uses: amenocal/stale@main
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          repo-name: ${{ matrix.repo }}
```

**Reply by jatin-mehrotra-colorkrew** [reply]
@andrewwise 

Thank for your this, I want how can I run this action on specific branches like test, prod, debug, dev ?

**Comment by maxileith** [comment]
You can create and use starter workflows organization wide: https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

**Reply by abhijit838** [reply]
Create GitHub apps to run action jobs and install it in your organisation.

**Comment by drewavos** [comment]
Alternative, if you don't want to rely on a third party github action.

```
name: Stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  get-org-repositories:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get org repositories
        id: get_repos
        run: |
          echo "repos=$(gh repo list <org> --no-archived --limit 1000 --json name | jq -c '.' >> "$GITHUB_OUTPUT"
    outputs:
      repos: ${{ steps.get_repos.outputs.repos }}

  run-for-repo:
    runs-on: ubuntu-latest
    needs: get-org-repositories
    strategy:
      matrix:
        repos: ${{ fromJson(needs.get-org-repositories.outputs.repos) }}
      fail-fast: false
    env:
      REPO_NAME: ${{ matrix.repos.name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          repository: neat-no/${{ matrix.repos.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Do work
        run: echo "Running for $REPO_NAME"
```
