### ISSUE TITLE
Docs for ascending

### ISSUE THREAD

**Issue by Renato66** [actions/stale#100]
the PR #97 was accepted but no examples in readme were made

**Comment by andymckay** [comment]
The list of features in https://github.com/actions/stale/blob/main/action.yml is quite long and most of these are not documented in the README at this point - just 2 extra example. The `action.yml` file is relatively detailed though and is referenced in the README.

I'm up for adding in more docs, but at this point it seems like we don't have a standard for this. Should I just copy what's in the actions.yml into the README? If so we could just write a script to convert the .yml into markdown or something 😄

**Comment by hross** [comment]
Totally up to you. if you think it's not worth documenting we can close it. or if you want to write the script... that would be pretty sweet. maybe even make an action that does that and outputs it to console as part of the build process so people can copy pasta it into their own docs.

**Comment by Renato66** [comment]
Maybe its missing some UX for the docs;
 I don't think that `Building and testing` section need to be on the first place
 More detailed examples on how to use could be implemented like this:
### Usage

Basic:
```yaml
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
        stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
```
<details><summary>Checkout more examples</summary>
<p>

### See [action.yml](./action.yml) For comprehensive list of options.

#### Run the bot to last 3 issues
Maybe you want to close only the last issues 

```yml
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_USER_TOKEN }}
        stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
        stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
```

#### Change bot apperance
If you want to change who added the labels, you can provide a user token

![image](https://user-images.githubusercontent.com/9284273/79672221-678bf080-81a6-11ea-908e-fb875772121a.png)

![image](https://user-images.githubusercontent.com/9284273/79672289-e123de80-81a6-11ea-9faa-237adc0873f0.png)

The [token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) will only need the `public_repo` scope

You will need to provide it as [secret](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) `GITHUB_USER_TOKEN`
and update the issue.yml repo-token with:
`repo-token: ${{ secrets.GITHUB_USER_TOKEN }}`


```yml
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_USER_TOKEN }}
        ascending: true
        operations-per-run: 3

```

</p>
</details>
