### ISSUE TITLE
Unable to reserve cache with key _state

### ISSUE THREAD

**Issue by kamaradclimber** [actions/stale#1090]
**Description:**

Processed issue cache cannot be saved, leading to going over same PRs over and over.

**Action version:**

b69b346013879cedbf50c69f572cd85439a41936

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Just wait for the action to launch

```
name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@b69b346013879cedbf50c69f572cd85439a41936
        id: stale
        with:
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label (or add the `never-stale` label) otherwise this PR will be closed in 30 days'
          close-pr-message: 'This PR has been closed because it remained without activity for 30 days and in "stale" state for 30 days. Of course, you can reopen it if necessary.'
          days-before-stale: 30
          days-before-close: 30
          close-pr-label: 'closed-reason: stale'
          exempt-pr-labels: 'never-stale'
          exempt-draft-pr: true # warning: this consumes 1 additional API request per PR
          operations-per-run: 100 # let’s increase batch size if necessary
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
```

**Expected behavior:**

Cache being used to go over all PR (1000+ in our repo).

**Actual behavior:**

Action go over the same 500PR.

In the action logs:
```
Github API rate remaining: 14887; reset at: Wed Sep 06 2023 06:27:06 GMT+0000 (Coordinated Universal Time)
state: persisting info about 459 issue(s)
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/logs-backend/logs-backend --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key _state, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/prod, Key: _state, Version: fa41d75081481069cfb6b92a5f83a94c6e06ef3ab2e6b762649ac5f86f46153f
```

Cache file `_state` does exist but has been created once and never updated apparently.
