### ISSUE TITLE
How to run only on PRs?

### ISSUE THREAD

**Issue by alper** [actions/stale#1112]
I would like stale to run only on PRs but not on issues. I don't see a way in the documentation to do s.

**Comment by dsame** [comment]
Hello alper, most of the operations have *-pr-* variant - they affect only PR's according to the documentation. Can you please clarify what namely operation do you want to be applied?

**Comment by alper** [comment]
I couldn't figure out how to not have it work on issues so I set the issue days to 999.

That should probably work long enough for my purposes.

**Comment by shmishra99** [comment]
@alper 
To opt out of the stale issue management for all issues, configure `days-before-issue-stale` and day-before-issue-closed`  with a value of -1.

**Comment by mosabua** [comment]
I am trying this out @shmishra99 .. I think it would be great to have this in the docs .. you want me to send a PR to add it once I confirmed it works?

**Comment by joaopgrassi** [comment]
> Hello alper, most of the operations have _-pr-_ variant - they affect only PR's according to the documentation. Can you please clarify what namely operation do you want to be applied?

This does not work. I have set up only the `*-pr` variant of configuration, but the bot still runs on issues because it seems there some defaults for `days-before-stale: 60` and `days-before-close: 7`.

You can see this in this example Action run: https://github.com/open-telemetry/semantic-conventions/actions/runs/7925571995/job/21638954263

```
Run actions/stale@v9
  with:
    repo-token: ***
    stale-pr-message: This PR was marked stale due to lack of activity. It will be closed in 7 days.
    close-pr-message: Closed as inactive. Feel free to reopen if this PR is still being worked on.
    exempt-pr-labels: bug,work in progress,experts needed
    exempt-draft-pr: true
    days-before-pr-stale: 15
    days-before-pr-close: 7
    days-before-stale: 60 <<<<<<<<<<<<<<<<<< I did not add this in my config
    days-before-close: 7 <<<<<<<<<<<<<<<<<< I did not add this in my config
    stale-issue-label: Stale
    close-issue-reason: not_planned
    stale-pr-label: Stale
    exempt-all-milestones: false
    operations-per-run: 30
    remove-stale-when-updated: true
    debug-only: false
    ascending: false
    delete-branch: false
    exempt-all-assignees: false
    enable-statistics: true
    ignore-updates: false
    include-only-assigned: false
```

My current config is: 

```
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR was marked stale due to lack of activity. It will be closed in 7 days.'
          close-pr-message: 'Closed as inactive. Feel free to reopen if this PR is still being worked on.'
          exempt-pr-labels: 'bug,work in progress,experts needed'
          exempt-draft-pr: true
          days-before-pr-stale: 15
          days-before-pr-close: 7
```
