### ISSUE TITLE
Actions fails if rate Limit is not enabled

### ISSUE THREAD

**Issue by ggabijaa** [actions/stale#1156]
**Description:**
When running action on schedule errors due to rateLimit. The actions is marked as successful but logs were showing errors:
<img width="550" alt="image" src="https://github.com/actions/stale/assets/59805033/50fc8e93-1b30-432d-b43c-802fa73bd150">

Is this expected behavior? Should action error out when rateLimit, not enabled?

**Action version:** V9

**Platform:** Rocky Linux

**Runner type:** Self-hosted

**Workfkow config:**  
```
name: Mark Stale Pull Requests

on:
  schedule:
    - cron: '0 1 * * *'

permissions:
  issues: write
  pull-requests: write


jobs:
  stale:
    runs-on: [self-hosted, rocky]
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 3
          stale-pr-label: 'stale'
          labels-to-remove-when-unstale: 'stale'
          days-before-close: -1
```
