### ISSUE TITLE
Add option to keep posting comment on stale issue.

### ISSUE THREAD

**Issue by VincentLanglet** [actions/stale#1209]
**Description:**

Currently the stale bot
- Add a label "stale"
- Poste a message "This is stale"

And then, if the user is doing nothing, finally close the issue.

But I'd like the bot to keep posting "This is stale" on the issue every day to ping the user until
- The issue is not stale
- Or the issue is closed

So I would like an option in order to force the actions to keep running on stale issue and re-post a comment.
Like a `comment-stale-issue: true` (false by default)

**Justification:**

I'm using the stale bot to post a message on issue under some conditions, like a missing label.
For instance
```
            -   name: Check for issues without priority
                uses: actions/stale@v9
                with:
                    ascending: false
                    days-before-stale: 7
                    days-before-pr-stale: -1
                    days-before-close: -1
                    ignore-updates: true
                    exempt-issue-labels: priority:low,priority:medium,priority:high,priority:critical
                    stale-issue-label: need:priority
                    stale-issue-message: >
                        This issue is missing a priority.
```

And I'd like that until the condition is met, the stale bot is still posting a new remember every day (when the github action is running), in order to ping the author which might have forgotten.

**Are you willing to submit a PR?**

- Sure, but I don't know how this work ; I assume the dev is not that hard, but I would help some explanations about the needed change and where is the core logic.
