### ISSUE TITLE
##[warning]performed 30 operations, exiting to avoid rate limit

### ISSUE THREAD

**Issue by glenn-jocher** [actions/stale#131]
Hello,

I see a rate limit warning on the stale action, and it appears it has not canvassed all the open issues in our repo. Not sure what the solution is. Any help would be appreciated, thanks in advance!
<img width="1178" alt="Screen Shot 2020-07-31 at 12 48 31 PM" src="https://user-images.githubusercontent.com/26833433/89071752-2f12bb80-d32c-11ea-8c0e-186ea7066175.png">

Our action yml is here:
https://github.com/ultralytics/yolov5/blob/master/.github/workflows/stale.yml
```yaml
name: Close stale issues
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-pr-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          days-before-stale: 30
          days-before-close: 5
          exempt-issue-label: 'documentation,tutorial'
```
