### ISSUE TITLE
Add support for adding close label

### ISSUE THREAD

**Issue by mollyIV** [actions/stale#134]
Currently there's no option for adding a dedicated label, when an issue / a pr is being closed. 

I'd like to propose adding two parameters to the action's interface:

```yaml
close-issue-label:
    description: 'The label to apply when an issue is closed.'

close-pr-label:
    description: 'The label to apply when a pull request is closed.'
```

No breaking changes, only opt-in.
