### ISSUE TITLE
Customize the identity of the current action executor

### ISSUE THREAD

**Issue by yi-Xu-0100** [actions/stale#161]
The execution identity of the current action is the creator of the repository using it. Can it be customized to allow it to indicate that this automatic action is generated by the bot? 

This idea comes from [the configuration of peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-git-username-and-email), you may need to add some parameters such as:

``` yml
with:
  user_name: 'github-actions[bot]'
  user_email: 'github-actions[bot]@users.noreply.github.com'
```

Thanks for all your works.🙂
