### ISSUE TITLE
Support exempt-from-milestones

### ISSUE THREAD

**Issue by derTobsch** [actions/stale#20]
I want every pr/issue that is defined in a milestone and `exempt-from-milestones` is true, that this pr/issue will not get staled/closed, because if a pr/issue is already defined in a milestone it is already recognized by the team and was planned. So there is no need to close/stale it.

```
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-from-milestones: true
```
