### ISSUE TITLE
New comments do not remove the Stale label

### ISSUE THREAD

**Issue by gergelyke** [actions/stale#21]
As raised in https://github.com/uber-web/baseui/pull/1892, it seems like new comments do not remove the Stale label. Do we miss anything in our configuration?

```yml
name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. If it's still valid, please remove the stale label or comment on the issue, otherwise this ticket will be closed in 5 days"
          days-before-stale: 30
          days-before-close: 5
```
