### ISSUE TITLE
Stale action not closing any PR or issue 

### ISSUE THREAD

**Issue by dhruvmanila** [actions/stale#216]
I am having a hard time figuring out what's the problem here. We are running the action every hour and according to the logs, the action is not going past a certain number of pull requests or issues. At first, I thought it might take time to go through the large number of PRs but there was no response.

Some examples:
https://github.com/TheAlgorithms/Python/pull/2798: This PR was marked stale 10 days ago and we have configured the action to close it in 7 days, yet there was no response.
https://github.com/TheAlgorithms/Python/issues/3096: The same problem exists for this issue.
And there are more.

Here's the configuration:
```yaml
name: Mark/Close stale issues and pull requests
on:
  schedule:
    - cron: "0 * * * *" # Run every hour
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: >
            ...
          close-issue-message: >
            ...
          stale-pr-message: >
            ...
          close-pr-message: >
            ...
```

Latest run logs:
```
Found issue: issue #3903 last updated 2020-11-19T17:00:58Z (is pr? true)
Found issue: issue #3899 last updated 2020-11-19T03:55:22Z (is pr? false)
Found issue: issue #3896 last updated 2020-11-18T11:27:26Z (is pr? false)
Found issue: issue #3893 last updated 2020-11-19T17:01:30Z (is pr? true)
Found issue: issue #3888 last updated 2020-11-13T22:28:51Z (is pr? false)
Found issue: issue #3887 last updated 2020-11-16T16:25:41Z (is pr? false)
...
...
Found issue: issue #3571 last updated 2020-11-19T03:03:51Z (is pr? true)
Found a stale pr
Checking for label on issue #3571
Issue #3571 marked stale on: 2020-11-19T03:03:51Z
Checking for comments on issue #3571 since 2020-11-19T03:03:51Z
Comments not made by actor or another bot: 0
Issue #3571 has been commented on: false
Issue #3571 has been updated: true
Stale pr is not old enough to close yet (hasComments? false, hasUpdate? true
...
...
Issue #3423 marked stale on: 2020-11-16T08:04:10Z
Checking for comments on issue #3423 since 2020-11-16T08:04:10Z
Comments not made by actor or another bot: 0
Issue #3423 has been commented on: false
Issue #3423 has been updated: true
Stale pr is not old enough to close yet (hasComments? false, hasUpdate? true
Warning: Reached max number of operations to process. Exiting.
```
