### ISSUE TITLE
Close issues / PRs immediately after adding the 'stale' label

### ISSUE THREAD

**Issue by NBprojekt** [actions/stale#28]
The behavior I'm looking for is that a issues / PRs gets immediately closed after the 'stale' label was added.

I thought this would do the thing but it did not close the issue after adding the label, the issue got closed 1 day after the label was added.

```
days-before-stale: 2
days-before-close: 0
```

Also is there a posibility to locked the issue after it was closed?

Inspired by Ionictron, [intended behavior](https://github.com/ionic-team/ionic/issues/13486#issuecomment-441088111)

**Comment by Spomky** [comment]
Hi,

I agree with this feature.
Also, having the possibility to immediately close an issue/PR would be nice e.g. for read only repositories.

Hoping it will be implemented.

**Comment by hross** [comment]
If you want this behavior I think you can do it now, you just need to execute the stale action when an issue label changes. You should be able to create an action like this that will trigger it immediately...

```
name: Trigger stale on issue label

on:
  issues:
    types: [labeled, unlabeled]
    
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
          stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
          days-before-stale: 2
          days-before-close: 0
```
