### ISSUE TITLE
Action runs but does nothing

### ISSUE THREAD

**Issue by MaicolBen** [actions/stale#37]
It is neither marking as stale or closing the PRs. The github log is:
<img width="396" alt="Screen Shot 2020-02-18 at 15 12 13" src="https://user-images.githubusercontent.com/3474627/74764764-12dcff80-5261-11ea-8575-23e57934c301.png">

**Comment by Aylr** [comment]
@MaicolBen Were you ever able to get this working?

**Comment by MaicolBen** [comment]
No, still not working, considering switching back to the bot one

**Comment by Aylr** [comment]
Thanks. I'm going to experiment with some of the forks. I'll let you know what I find.

**Comment by Aylr** [comment]
This action isn't doing anything because there is no compiled .js file, only the typescript file.

**Comment by Aylr** [comment]
I got this to work! The key is that the javascript file path was missing on release 1.1.0. Add the `        main: 'lib/main.js'` to the keys under the `with` section.

```
name: "Close stale issues"
on:
  issues:
    types: [opened, reopened]
  schedule:
  - cron: "*/15 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ...
        main: 'lib/main.js'
```
