### ISSUE TITLE
Question: How does "remove stale label or comment" reset the clock?

### ISSUE THREAD

**Issue by pllim** [actions/stale#372]
Based on this example adapted from your README:

```yaml
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          days-before-stale: 30
          days-before-close: 5
```

Let's say I have a PR that with no activity. On day 30 since last activity, the bot slaps a "Stale" label on it and issues `stale-pr-message`. When someone sees that and comments (not a new push commit, but merely commenting on GitHub) and does not bother to remove the "Stale" label (which is allowed, given the "or" statement in the message), does the bot then wait till day 60 before issuing another `stale-pr-message`, or does it go ahead and close it anyway on day 35, given that the PR still has the "Stale" label?

I am asking because I see you also have `remove-stale-when-updated`, which implies that the "Stale" label needs to be removed to reset the clock, so "or comment" isn't really accurate in this case (and also is confusing given you don't need `remove-stale-when-comment` option to have it activated consistently as a push event).

Thank you!
