### ISSUE TITLE
Bad grammar on log output for "This issue hasn't a stale label"

### ISSUE THREAD

**Issue by HonkingGoose** [actions/stale#398]
## Problem

The log output for issues that lack a `stale` label uses bad grammar:`This issue hasn't a stale label`.
If we write this out in full it says: `This issue has not a stale label`, which is a bit weird.

## Configuration

```yml
# Go to https://github.com/actions/stale for the full documentation of these options.

name: 'Close stale bug reports that lack reproduction'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.18
        with:
          # Rate limit per run, (defaults to 30, but we've increased it to 40 for now).
          operations-per-run: 40

          # Only issues with both `reproduction:needed` and `type:bug` will be touched by the stale bot.
          only-issue-labels: 'reproduction:needed,type:bug'

          # A issue that has any assignee is getting worked on, so is exempt from stale bot.
          exempt-all-issue-assignees: true

          # Remove stale label from issue/PR on updates or comments, defaults to true.
          remove-stale-when-updated: true

          # Wait 14 days until making issue stale and posting a message.
          days-before-issue-stale: 14
          stale-issue-message: 'When a bug has been marked as needing a reproduction, it means nobody can work on it until one is provided. In cases where no reproduction is possible, or the issue creator does not have the time to reproduce, we unfortunately need to close such issues as they are non-actionable and serve no benefit by remaining open. This issue will be closed after 7 days of inactivity.'
          stale-issue-label: 'stale'

          # Close out issue after 7 stale days.
          days-before-issue-close: 7
          close-issue-message: 'This bug report has been closed as we need a reproduction to work on this. If the original poster or anybody else with the same problem discovers that they can reproduce it, please create a new issue, and reference this issue.'
```

## Logs:

Copy/paste of the log ouput for the processing of a issue for full context:

```
[#9239] Found this pull request last updated 2021-03-21T23:34:04Z
[#9239] The option "onlyLabels" was not specified. Continuing the process for this pull request
[#9239] Days before pull request stale: 60
[#9239] Skipping pull request due to empty stale message
[#9238] Found this issue last updated 2021-03-21T21:44:18Z
[#9238] The option "onlyLabels" was specified to only processed the issues and pull requests with all those labels (2)
[#9238] All the required labels are present on this issue. Continuing the process
[#9238] Days before issue stale: 14
[#9238] The issue is not closed nor locked. Trying to remove the close label...
[#9238] There is no close label on this issue. Skip
[#9238] This issue hasn't a stale label
[#9238] This issue has no assignee
[#9238] Skip the assignees checks
[#9238] Not marking as stale: shouldBeStale=false, shouldMarkAsStale=true
```

## Proposed solution:

Change `This issue hasn't a stale label` -> `This issue has no stale label`.
This way we're also consistent with the `This issue has no assignee` style of log output. 😉
