### ISSUE TITLE
Error: Get issues for repo error: Resource not accessible by integration

### ISSUE THREAD

**Issue by Samira-El** [actions/stale#502]
## Describe your issue

Stale action logs an error regarding getting issues. but also doesn't perform any operations despite the logs mentioning 28 op performed:
```
Run actions/stale@v3
Starting the stale action process...
Error: Get issues for repo error: Resource not accessible by integration
No more issues found to process. Exiting...
Statistics:
Operations performed: 28
```

The repository doesn't have issues enabled, but even after I enabled them, it's still throwing same error.

I enabled `debug-only` and `enable-statistics` but there were no additional logs.

## Your stale action configuration

```yml
jobs:
  stale:
    runs-on: ...
    permissions:
              pull-requests: write
    steps:
       - uses: actions/stale@v3
         with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.'
                days-before-pr-stale: 30
```

**Comment by C0ZEN** [comment]
@Samira-El can you try with:

```yaml
jobs:
  stale:
    runs-on: ...
    permissions:
  	  issues: write
      pull-requests: write
```
