### ISSUE TITLE
Bot updates shouldn't count as "regular" updates

### ISSUE THREAD

**Issue by pattacini** [actions/stale#506]
## Describe your issue
It seems that the updates that the stale bot applies to an issue do count as regular updates so we end up assigning and soon afterward removing the `stale` label, for example. 

## Your stale action configuration

My repository is https://github.com/robotology/icub-tech-support whose workflow is the following:

```yml
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        with:
          stale-issue-message: 'This issue has been automatically marked as stale...'
          close-issue-message: 'This issue has been automatically closed...'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: stale
          exempt-issue-labels: pinned
          operations-per-run: 200
```

## Further context
I got my hunch by looking at what happened for example to a particular issue: see https://github.com/robotology/icub-tech-support/issues/1096#issuecomment-860171246.

Here's below the corresponding action log:

```
[#1096] Issue #1096
  [#1096] Found this issue last updated at: 2021-06-13T08:05:32Z
  [#1096] The option only-labels (​https://github.com/actions/stale#only-labels​) was not specified
  [#1096] └── Continuing the process for this issue
  [#1096] Days before issue stale: 60
  [#1096] The issue is not closed nor locked. Trying to remove the close label...
  [#1096] ├── The close-issue-label (​https://github.com/actions/stale#close-issue-label​) option was not set
  [#1096] └── Skipping the removal of the close label
  [#1096] This issue has a stale label
  [#1096] The option any-of-labels (​https://github.com/actions/stale#any-of-labels​) was not specified
  [#1096] └── Continuing the process for this issue
  [#1096] This issue has no milestone
  [#1096] └── Skip the milestones checks
  [#1096] The option exempt-all-assignees (​https://github.com/actions/stale#exempt-all-assignees​) is disabled. Only some specific assignees on this issue will skip the stale process
  [#1096] ├── The option exempt-issue-assignees (​https://github.com/actions/stale#exempt-issue-assignees​) is disabled. No specific assignee can skip the stale process for this issue
  [#1096] ├── The option exempt-assignees (​https://github.com/actions/stale#exempt-assignees​) is disabled. No specific assignee can skip the stale process for this issue
  [#1096] ├── No assignee option was specified to skip the stale process for this issue
  [#1096] └── Skip the assignees checks
  [#1096] This issue is already stale
  [#1096] Checking for label on this issue
  [#1096] Issue marked stale on: 2021-06-13T08:05:32Z
  [#1096] Checking for comments on issue since: 2021-06-13T08:05:32Z
  [#1096] Comments not made by actor or another bot: 0
  [#1096] Issue has been commented on: false
  [#1096] Days before issue close: 7
  [#1096] Issue has been updated: true
  [#1096] The option remove-stale-when-updated (​https://github.com/actions/stale#remove-stale-when-updated​) is: true
  [#1096] The stale label should not be removed due to an update
  [#1096] The option remove-stale-when-commented (​https://github.com/actions/stale#remove-stale-when-commented​) is: true
  [#1096] The stale label should not be removed due to a comment
  [#1096] Remove the stale label since the issue has an update and the workflow should remove the stale label when updated
  [#1096] The issue is no longer stale. Removing the stale label...
  [#1096] Removing the label "stale" from this issue...
  [#1096] The label "stale" was removed
  [#1096] Skipping the process since the issue is now un-stale
  [#1096] 2 operations consumed for this issue
```

From the log, we can extract the following two relevant info:
- `Found this issue last updated at: 2021-06-13T08:05:32Z`
- `Issue marked stale on: 2021-06-13T08:05:32Z`

Clearly, the update time matches the time when the issue was marked as stale and as such the stale label gets removed.

For the time being, I'll be trying to use the param `remove-stale-when-updated: false` to get around this, although I think bot updates shouldn't count as regular updates.

Am I missing something?
