### ISSUE TITLE
`stale` label not removed from issue that had an update

### ISSUE THREAD

**Issue by dfawley** [actions/stale#509]
## Describe your issue

`stale` label not removed from issue that had an update.

## Your stale action configuration

https://github.com/grpc/grpc-go/blob/master/.github/workflows/stale.yml

```yml
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 6
        days-before-close: 7
        only-labels: 'Status: Requires Reporter Clarification'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        operations-per-run: 60
        stale-issue-message: ...
        stale-pr-message: ...
```

## Further context

Issue: https://github.com/grpc/grpc-go/issues/4522
Run: https://github.com/grpc/grpc-go/runs/2841504434?check_suite_focus=true#step:2:94

```
[#4522] Found this issue last updated at: 2021-06-16T15:04:02Z
[#4522] The option only-labels (​https://github.com/actions/stale#only-labels​) was specified to only process issues and pull requests with all those labels (1)
[#4522] ├── All the required labels are present on this issue
[#4522] └── Continuing the process for this issue
[#4522] Days before issue stale: 6
[#4522] The issue is not closed nor locked. Trying to remove the close label...
[#4522] There is no close label on this issue. Skip
[#4522] This issue has a stale label
[#4522] The option any-of-labels (​https://github.com/actions/stale#any-of-labels​) was not specified
[#4522] └── Continuing the process for this issue
[#4522] This issue has no milestone
[#4522] └── Skip the milestones checks
[#4522] The option exempt-all-assignees (​https://github.com/actions/stale#exempt-all-assignees​) is disabled. Only some specific assignees on this issue will skip the stale process
[#4522] ├── The option exempt-issue-assignees (​https://github.com/actions/stale#exempt-issue-assignees​) is disabled. No specific assignee can skip the stale process for this issue
[#4522] ├── The option exempt-assignees (​https://github.com/actions/stale#exempt-assignees​) is disabled. No specific assignee can skip the stale process for this issue
[#4522] ├── No assignee option was specified to skip the stale process for this issue
[#4522] └── Skip the assignees checks
[#4522] This issue is already stale
[#4522] Checking for label on this issue
[#4522] Issue marked stale on: 2021-06-16T04:52:42Z
[#4522] Checking for comments on issue since: 2021-06-16T04:52:42Z
[#4522] Comments not made by actor or another bot: 0
[#4522] Issue has been commented on: false
[#4522] Days before issue close: 7
[#4522] Issue has been updated: true
[#4522] Stale issue is not old enough to close yet (hasComments? false, hasUpdate? true)
[#4522] 1 operation consumed for this issue
```

Entries of note from the log above:
```
Found this issue last updated at: 2021-06-16T15:04:02Z
Issue marked stale on: 2021-06-16T04:52:42Z
Checking for comments on issue since: 2021-06-16T04:52:42Z
Comments not made by actor or another bot: 0
Issue has been commented on: false
```

Note that it sees my update at 15:04:02, after the marked stale time of 04:52:42.  But it says "Comments not made by actor or another bot: 0".  What does "actor" mean in this instance?
