### ISSUE TITLE
Option stale-issue-message required?

### ISSUE THREAD

**Issue by jasongrout** [actions/stale#521]
## Describe your issue

We have omitted the `stale-issue-message` option (in fact, we still have `skip-stale-issue-message` set, but that seems ignored now). According to the docs at https://github.com/actions/stale#stale-issue-message:

> You can skip the comment sending by omitting the option or by passing an empty string.

So it seems since we have omitted the `stale-issue-message` parameter, we should be fine - issues should be marked stale without a comment. However, in our logs, we see  https://github.com/jupyterlab/jupyterlab/runs/2994705101?check_suite_focus=true#step:2:3995 :

>  [#5869] Skipping this issue because it should be marked as stale based on the option days-before-stale (​https://github.com/actions/stale#days-before-stale​) (30) but the option stale-issue-message (​https://github.com/actions/stale#stale-issue-message​) is not set

and the relevant issue is not marked stale. Is giving a `stale-issue-message` mandatory now, with an empty string signifying no message?

## Your stale action configuration

https://github.com/jupyterlab/jupyterlab/blob/cd7ac23f738c9a8792bbb76a256e84a82535446c/.github/workflows/answered.yml

```yml
name: 'Close answered issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          skip-stale-issue-message: true
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'status:Closing as Answered'
          only-issue-labels: 'status:Answered'

```
