### ISSUE TITLE
Action does not run or show in "actions" tab.

### ISSUE THREAD

**Issue by charlesomer** [actions/stale#529]
## Describe your issue
Unable to run action at all.

## Your stale action configuration

```yml
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue has been inactive for 60 days so will be closed 7 days from now. To prevent this, please remove the "stale" label or post a comment.'
          stale-pr-message: 'This PR has been inactive for 60 days so will be closed 7 days from now. To prevent this, please remove the "stale" label or post a comment.'
          # These are the defaults at the time of writing. https://github.com/marketplace/actions/close-stale-issues
          # days-before-stale: 60
          # days-before-close: 7
```

## Further context
I am not sure what I'm doing wrong - I can't think of anything else to try at the moment.
