### ISSUE TITLE
Stale action passes while exceeding the `operations-per-run` limit

### ISSUE THREAD

**Issue by HonkingGoose** [actions/stale#536]
## Describe your issue

Stale action reports "passing" while exceeding the `operations-per-run` limit.
I'd have expected the Action to "Throw a error" and report back as "failed".

## Your stale action configuration

I use the latest version of the action, which is `v4.0.0` right now.
The new behavior on the `operations-per-run` is really limiting the amount of issues that it can process:

```
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to the operations-per-run (​https://github.com/actions/stale#operations-per-run​) option which is currently set to 40
Statistics:
Processed items: 260
├── Processed issues: 220
└── Processed PRs   : 40
New stale items: 12
├── New stale issues: 1
└── New stale PRs   : 11
Added items labels: 12
├── Added issues labels: 1
└── Added PRs labels   : 11
Added issues comments: 1
Fetched items: 300
Fetched items events: 12
Fetched items comments: 12
Operations performed: 40
```

Link to action overview for this run: https://github.com/renovatebot/renovate/actions/runs/1050964683

The full stale bot configuration:

```yml
# Go to https://github.com/actions/stale for the full documentation of these options.

name: 'Close stale bug reports that lack reproduction'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@cdf15f641adb27a71842045a94023bef6945e3aa # renovate: tag=v4.0.0
        with:
          # Rate limit per run, (defaults to 30, but we've increased it to 40 for now).
          operations-per-run: 40

          # Only issues with both `reproduction:needed` and `type:bug` will be touched by the stale bot.
          only-issue-labels: 'reproduction:needed,type:bug'

          # A issue that has any assignee is getting worked on, so is exempt from stale bot.
          exempt-all-issue-assignees: true

          # Remove stale label from issue/PR on updates or comments, defaults to true.
          remove-stale-when-updated: true

          # Wait 14 days until making issue stale and posting a message.
          days-before-issue-stale: 14
          stale-issue-message: 'When a bug has been marked as needing a reproduction, it means nobody can work on it until one is provided. In cases where no reproduction is possible, or the issue creator does not have the time to reproduce, we unfortunately need to close such issues as they are non-actionable and serve no benefit by remaining open. This issue will be closed after 7 days of inactivity.'
          stale-issue-label: 'stale'

          # Close out issue after 7 stale days.
          days-before-issue-close: 7
          close-issue-message: 'This bug report has been closed as we need a reproduction to work on this. If the original poster or anybody else with the same problem discovers that they can reproduce it, please create a new issue, and reference this issue.'
```

## Further context

The only way I can see that I hit the limit is by:

- Checking the logs
- Noticing not all stale bug reports are getting closed

I'd like the action to fail in a more obvious way like:

- Throw error and fail completely
- Creating a issue on the repository to report that the limit was exceeded

I don't know if this kind of behavior was considered and rejected?

---

EDIT: I see the action does pass some "annotations", but these don't result in GitHub warning you about it, I think?
