### ISSUE TITLE
Stale action deleted default branch in a PR

### ISSUE THREAD

**Issue by andygup** [actions/stale#543]
## Describe your issue

The bot successfully deleted a PR, however it deleted BOTH the default branch and the child branch. `delete-branch` was set to `true` but we expected it to only delete the child branch, not parent and child. 

Looking over this repo, I also noticed we are running v3 and that v4 is now available. We'll need to upgrade but this was serious enough of an issue that we want to find out why this problem happened before reactivating the bot.

Reference: https://github.com/actions/stale#delete-branch

## Your stale action configuration

```yml
name: "Close stale issues"

# Controls when the workflow will run. 
on:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # stale:
  stale-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. If you need additional assistance please contact Technical Support. Thank you for your contributions."
          close-issue-message: "This issue has been automatically closed due to inactivity. If you need additional assistance please contact Technical Support."
          stale-pr-message: "This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. If you need additional assistance please contact Technical Support. Thank you for your contributions."
          close-pr-message: "This PR has been automatically closed due to inactivity. If you need additional assistance please contact Technical Support."          
          only-labels: null
          days-before-stale: 365          
          days-before-close: 31
          delete-branch: true

```

## Further context

N/A
