### ISSUE TITLE
[Question] Definition of activity for a specified amount of time

### ISSUE THREAD

**Issue by giulitn** [actions/stale#557]
## The problem

So I have specified on the yml file '`days-before-issue-stale: 60`'
The thing is I'm not quite sure how is the rule _"have had no activity for a specified amount of time."_ considered?
I currently have about ~200 issues with the Stale label, but if I filter in the search engine by "is:open is:issue updated:<2021-06-30" for example, the result is about ~1000 issues. 
Is it a bug or do these functionalities use different definitions?

```
name: Mark stale issues

on:
  schedule:
    - cron: "15 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 60 days with no activity" 
          days-before-issue-stale: 60
          stale-issue-label: "Stale"
          days-before-issue-close: -1 # 
          ascending: true
          operations-per-run: 500
```
