### ISSUE TITLE
Error: HttpError

### ISSUE THREAD

**Issue by dimisjim** [actions/stale#577]
## Describe your issue

Got what the title says, just once. Have ran this action hundreds of times by now.

**Comment by flaxel** [comment]
Can you add some more information? A screenshot of the logs?

**Comment by dimisjim** [comment]
Sure, here you go: 
![image](https://user-images.githubusercontent.com/6890249/134944811-43ba6619-d18b-4a39-8e3b-ab3e56373005.png)

**Comment by flaxel** [comment]
How does your workflow look like? What configuration did you use?

**Comment by dimisjim** [comment]
>How does your workflow look like? What configuration did you use?

Pretty standard one:

```
name: Close stale PRs

on:
  schedule:
    - cron: '0 17 * * 1-5'

jobs:

  stale:
    runs-on: [self-hosted, dynamic]

    env:
      pr-stale: 30
      pr-close: 3

    steps:
      - uses: actions/stale@v3
        with:
          stale-pr-message: >-
            This PR has been marked as `Stale`, and thus will be closed in ${{ env.pr-close }} days, because it has been open for at least ${{ env.pr-stale }} days with no activity :construction_worker:.
            <br/>Remove the stale label or leave a comment, if you still want to keep it open.
            <br/><br/>This helps the repos' maintainers to distinguish active from inactive PRs.
          close-pr-message: >-
            This PR was closed because it remained inactive for at least ${{ env.pr-close }} days, after being marked as `Stale`.
          days-before-pr-stale: ${{ env.pr-stale }}
          days-before-pr-close: ${{ env.pr-close }}
```

>I tried to reproduce the error but I was not successful.

Same here, like I said in the issue description, it has worked hundreds of times, but it failed once, with the vague httpError

>Can you share the repo or the complete log?

No, it's a private repo.
