### ISSUE TITLE
How to use for a private repository?

### ISSUE THREAD

**Issue by poloka** [actions/stale#585]
I did not see any notation within the README on how to configure when accessing private repositories.  The repositories I work with require a GitHub personnel access token for authentication in retrieval of their contents.
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Is there a way to configure the action to utilize this token?

**Comment by wimo7083** [comment]
This is the entirety of my github action configuration for an `internal` repository, I don't know if there's a difference in private vs internal but you could try this out.

```yaml
name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch: {}

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: stale
          stale-pr-message: 'This PR has been marked as stale because it has been open for 7 days with no activity.  To prevent this PR from being closed in 7 days, remove the `stale` label or comment on this PR.'
          close-pr-message: 'This PR has been closed because it has been marked as `stale` for 7 days.'
          days-before-pr-stale: 7
          days-before-pr-close: 7 # days after stale, not total days.
          days-before-issue-close: -1
```

This relies on the [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow).
