### ISSUE TITLE
delete branch is not working due to permission problem

### ISSUE THREAD

**Issue by alexInhert** [actions/stale#587]
This is my configuration:

```
# https://github.com/actions/stale
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 9 * * *'
permissions:
  # All other permissions are set to none
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had recent activity.
          days-before-pr-stale: 90
          days-before-pr-close: 5
          exempt-pr-labels: 'pinned'
          remove-pr-stale-when-updated: true
          delete-branch: true
          ascending: true
          operations-per-run: 50
```

The job runs as expected committing on PRs and setting the stale label however the delete-branch doesn't work.
In the log I see:

`�[97m�[34m[#1288]�[39m Error when deleting the branch "�[36fixingissue�[39m" from pull request: Resource not accessible by integration�[39m`

Documentation specify that all is needed is  `pull-requests: write` permission which is set. What is the problem?
