### ISSUE TITLE
ignore-updates is not working as expected

### ISSUE THREAD

**Issue by peimanja** [actions/stale#593]
## Describe your issue
we were very interested to try `ignore-updates` option to just close PRs based on how old they are but it's not always working which is weird.

## Your stale action configuration

```yml
name: 'Cleanup'
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

env:
  STALE_DAYS_OLD: 7
  CLOSE_AFTER_STALE_DAYS_OLD: 7
  STALE_IGNORE_LABEL: ignore-stale
  DELETE_BRANCHES_DAYS_OLD: 90

jobs:
  stale-prs:
    ...
    steps:
      ...
      - name: 'Close Stale PRs'
        uses: actions/stale@main
        with:
          repo-token: "${{ steps.github-token.outputs.token }}"
          stale-pr-message: "This PR is stale because it has been open for more than ${{ env.STALE_DAYS_OLD }} days. Remove stale label or add `${{ env.STALE_IGNORE_LABEL }}` label otherwise this PR will be closed and associated branch will be deleted in ${{ env.CLOSE_AFTER_STALE_DAYS_OLD }} days."
          close-pr-message: "This PR was closed and associated branch was deleted."
          exempt-pr-labels: ${{ env.STALE_IGNORE_LABEL }}
          ignore-updates: true
          delete-branch: true
          remove-stale-when-updated: false
          operations-per-run: 100
          days-before-pr-stale: ${{ env.STALE_DAYS_OLD }}
          days-before-pr-close: ${{ env.CLOSE_AFTER_STALE_DAYS_OLD }}
```

## Further context

Here is the log output for one of the PRs:
```
[#1241] Pull request #1241
  [#1241] Found this pull request last updated at: 2021-10-13T19:10:38Z
  [#1241] The option only-labels (​https://github.com/actions/stale#only-labels​) was not specified
  [#1241] └── Continuing the process for this pull request
  [#1241] Days before pull request stale: 7
  [#1241] The pull request is not closed nor locked. Trying to remove the close label...
  [#1241] ├── The close-pr-label (​https://github.com/actions/stale#close-pr-label​) option was not set
  [#1241] └── Skipping the removal of the close label
  [#1241] This pull request has a stale label
  [#1241] The option any-of-labels (​https://github.com/actions/stale#any-of-labels​) was not specified
  [#1241] └── Continuing the process for this pull request
  [#1241] This pull request has no milestone
  [#1241] └── Skip the milestones checks
  [#1241] This pull request has no assignee
  [#1241] └── Skip the assignees checks
  [#1241] This pull request is already stale
  [#1241] Checking for label on this pull request
  [#1241] Pull request marked stale on: 2021-09-17T17:46:49Z
  [#1241] Checking for comments on pull request since: 2021-09-17T17:46:49Z
  [#1241] Comments that are not the stale comment or another bot: 0
  [#1241] Pull request has been commented on: false
  [#1241] Days before pull request close: 7
  [#1241] Pull request has been updated: true
  [#1241] The option remove-stale-when-updated (​https://github.com/actions/stale#remove-stale-when-updated​) is: false
  [#1241] The stale label should be removed if all conditions met
  [#1241] Stale pull request is not old enough to close yet (hasComments? false, hasUpdate? true)
  [#1241] 1 operation consumed for this pull request
```
