### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by withinfocus** [actions/stale#600]
## Describe your issue

Attempted to use the Action after reading the documentation here, but when trying to roll out our configuration we noticed `exempt-draft-pr` isn't available / used, along with no doubt other changes since 4.0.0 in July. Requesting a new release be cut.

## Your stale action configuration

(clipped for brevity)

```yml
steps:
  - uses: actions/stale@v4
    with:
      exempt-draft-pr: true
```
