### ISSUE TITLE
`days-before-issue-close` appears to take double the stated value of days

### ISSUE THREAD

**Issue by ciaranevans** [actions/stale#606]
## Describe your issue

Hey folks,

We're using `actions/stale` in a fair few of the [Chaos Toolkit](https://github.com/chaostoolkit) repositories and I've been noticing that issues are closed 14 days after being marked as stale, even though I've specified `7` days in the configuration.

For example, in our `chaostoolkit-aws` repository, we have this action defined: https://github.com/chaostoolkit-incubator/chaostoolkit-aws/blob/master/.github/workflows/close-stale-issues.yaml

```yaml

name: Close Stale Issues
on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 00:00
    - cron: '0 0 * * 0'

jobs:
  close-stale-issues:
    permissions:
      issues: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v4
        with:
          operations-per-run: 200
          stale-issue-message: 'This Issue has not been active in 365 days. To re-activate this Issue, remove the `Stale` label or comment on it. If not re-activated, this Issue will be closed in 7 days.'
          close-issue-message: 'This Issue was closed because it was not reactivated after 7 days of being marked `Stale`.'
          days-before-issue-stale: 365
          days-before-issue-close: 7
          # For now, don't mark PRs stale and don't close them
          days-before-pr-stale: -1
          days-before-pr-close: -1
```

But if you look at the history of a stale issue in the repository, such as this one: https://github.com/chaostoolkit-incubator/chaostoolkit-aws/issues/83

The action marked it stale 14 days ago here: https://github.com/chaostoolkit-incubator/chaostoolkit-aws/issues/83#issuecomment-939858640, but only closed it yesterday: https://github.com/chaostoolkit-incubator/chaostoolkit-aws/issues/83#issuecomment-950236541

I don't think this is the cron jobs fault, but I may be wrong...?

Would appreciate any suggestions 😄
