### ISSUE TITLE
Customize bot name/avatar

### ISSUE THREAD

**Issue by pdcmoreira** [actions/stale#61]
Hi,

Is it possible to customize the bot's name and avatar?
Sorry if this question doesn't belong here, I've searched all around and couldn't find an answer.

**Comment by mollyIV** [comment]
Hello @pdcmoreira 👋 

> Is it possible to customize the bot's name and avatar?

I assume you are talking about customizing a bot's name and avatar when adding the comments to issues / pull requests via GH Actions. If that's the case, then yes, it is possible. 

All you need to do is to use a GitHub Token of a bot / user that you'd like to add the comments per. For example:

```yaml
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.BOT_GITHUB_TOKEN }} # <--- provide bot's token here via secrets
        stale-issue-message: '...'
        days-before-stale: 30
        days-before-close: 5
```

Please let me know if that helped 🙇
