### ISSUE TITLE
Draft PRs are not staled

### ISSUE THREAD

**Issue by flaxel** [actions/stale#611]
## Describe your issue

The draft PRs are not staled. In the logs you can read that they were always updated one day ago. But this is not the case. 

## Your stale action configuration

```yml
name: Stale PRs

on:
  schedule:
  - cron: "0 0 * * 1-5"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v4
      with:
        days-before-stale: 14
        stale-pr-message: 'This PR has been automatically marked as stale because there has been no recent activity in the last 21 days. It will be closed in 7 days if no further activity.'
        delete-branch: true
```

## Further context

```
[#2059] Pull request #2059
  [#2059] Found this pull request last updated at: 2021-11-14T22:56:19Z
  [#2059] The option only-labels (​https://github.com/actions/stale#only-labels​) was not specified
  [#2059] └── Continuing the process for this pull request
  [#2059] Days before pull request stale: 14
  [#2059] The pull request is not closed nor locked. Trying to remove the close label...
  [#2059] ├── The close-pr-label (​https://github.com/actions/stale#close-pr-label​) option was not set
  [#2059] └── Skipping the removal of the close label
  [#2059] This pull request hasn't a stale label
  [#2059] The option any-of-labels (​https://github.com/actions/stale#any-of-labels​) was not specified
  [#2059] └── Continuing the process for this pull request
  [#2059] This pull request has no milestone
  [#2059] └── Skip the milestones checks
  [#2059] This pull request has no assignee
  [#2059] └── Skip the assignees checks
  [#2059] This pull request is not stale
  [#2059] This pull request should not be stale based on the last update date the 14-11-2021 (2021-11-14T22:56:19Z)
```
