### ISSUE TITLE
Cannot seem to use the stale action

### ISSUE THREAD

**Issue by Nokel81** [actions/stale#612]
## Describe your issue
I have tried setting up `actions/stale` but so far every attempt has resulted in the following output:

```
Error: Unable to resolve action `actions/stale@4.0.0`, unable to find version `4.0.0`
```

or 

```
Error: Unable to resolve action `actions/stale@4`, unable to find version `4`
```

## Your stale action configuration

```yml
name: Cull Stale Issues
on:
  schedule:
    - cron: "30 1 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/stale@4.0.0
        with:
          only-issue-labels: "needs-information"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # -1 here means that PRs will never be marked as stale
          days-before-pr-stale: -1
```

## Further context

![Screen Shot 2021-11-15 at 9 25 42 AM](https://user-images.githubusercontent.com/8225332/141798371-16637cc7-1b9c-4b06-8a0d-7e9ceefa81eb.png)
https://github.com/lensapp/lens/actions/runs/1446954745
