### ISSUE TITLE
[Question]: How to split the operations between issues and PRs

### ISSUE THREAD

**Issue by HapThorin** [actions/stale#636]
In this [action](https://github.com/huaweicloud/Sermant/actions/runs/1612911977), I attempt to split the operations into two steps, one for issues and the other one for PRs. But, from the executing log, I found both of two steps scanned issues and PRs. Considering that PR is processed more timely than issue, I think it necessary to separate them. Therefore, I am here to find a correct way to deal with it. Here is my configuration looks like: 

```yml
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.1.0
        name: Auto Close Stale Issues
        with:
          stale-issue-label: Stale
          stale-issue-message: >
            This issue seems to be **Stale**. We will close it in a few days.
          close-issue-message: >
            We close this issue because it hasn't been updated in a while. Remove **Stale** label if you want to reopen it.
          days-before-issue-stale: 29
          days-before-issue-close: 1
          operations-per-run: 80
      - uses: actions/stale@v4.1.0
        name: Auto Close Stale PRs
        with:
          stale-pr-label: Stale
          stale-pr-message: >
            This PR seems to be **Stale**. We will close it in a few days.
          close-pr-message: >
            We close this PR because it hasn't been updated in a while. Remove **Stale** label if you want to reopen it.
          days-before-pr-stale: 14
          days-before-pr-close: 1
          operations-per-run: 30
```

I can only merge this two steps and increase the value of `operations-per-run` to deal with it for the time being. But this is only an expedient measure. I really hope to find the correct way.
