### ISSUE TITLE
4.1.0 - workflow does not flag issues opened before 01.01.2022

### ISSUE THREAD

**Issue by MartinHahner** [actions/stale#678]
## Describe your issue

I created a [workflow](https://github.com/open-mmlab/OpenPCDet/blob/master/.github/workflows/close_stale_issues.yml) in an attempt to flag many old / _stale_ github issues.
However, the workflow did not flag stale issues that were opened before 01.01.2022 (see [here](https://github.com/open-mmlab/OpenPCDet/issues?page=2&q=is%3Aissue+is%3Aopen)).
Issue #731 and older are not getting marked correctly.

## Your stale action configuration

```yml
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4.1.0
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
