### ISSUE TITLE
Unexpected input ignore-updates

### ISSUE THREAD

**Issue by gabsmprocha** [actions/stale#680]
## Describe your issue

cant use ignore-pr-updates or ignore-updates parameter

## Your stale action configuration

```yml
 close-issues:
        runs-on: ubuntu-latest
        permissions:
          issues: write
          pull-requests: write
        steps:
          - uses: actions/stale@v3
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              stale-pr-message: 'This PR is stale because it has been open for 3 days. Remove stale label or this PR will be closed in 3 days.'
              days-before-pr-stale: 5
              days-before-pr-close: 3
              ignore-pr-updates: true
```

## Further context

Warning: Unexpected input(s) 'ignore-pr-updates', valid inputs are ['repo-token', 'stale-issue-message', 'stale-pr-message', 'close-issue-message', 'close-pr-message', 'days-before-stale', 'days-before-issue-stale', 'days-before-pr-stale', 'days-before-close', 'days-before-issue-close', 'days-before-pr-close', 'stale-issue-label', 'close-issue-label', 'exempt-issue-labels', 'stale-pr-label', 'close-pr-label', 'exempt-pr-labels', 'exempt-milestones', 'exempt-issue-milestones', 'exempt-pr-milestones', 'exempt-all-milestones', 'exempt-all-issue-milestones', 'exempt-all-pr-milestones', 'only-labels', 'any-of-labels', 'any-of-issue-labels', 'any-of-pr-labels', 'only-issue-labels', 'only-pr-labels', 'operations-per-run', 'remove-stale-when-updated', 'remove-issue-stale-when-updated', 'remove-pr-stale-when-updated', 'debug-only', 'ascending', 'skip-stale-pr-message', 'skip-stale-issue-message', 'delete-branch', 'start-date', 'exempt-assignees', 'exempt-issue-assignees', 'exempt-pr-assignees', 'exempt-all-assignees', 'exempt-all-issue-assignees', 'exempt-all-pr-assignees', 'enable-statistics']
