### ISSUE TITLE
Re-opened issues with the stale tag do not have the tag removed (v4.*)

### ISSUE THREAD

**Issue by SierraKomodo** [actions/stale#693]
## Describe your issue
Issues that were previously closed by the stale action do not auto-remove the stale tag when re-opened with a comment despite default configuration being to remove the stale tag on updates.

## Your stale action configuration
```yml
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue has not been updated in 30 days, and will close in 5 days from now if no updates are made.'
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-stale: -1
          days-before-pr-close: -1
          only-issue-labels: 'Runtime Error'

```

## Further context
Issue that displays the problem: https://github.com/Baystation12/Baystation12/issues/31045
