### ISSUE TITLE
Close PR's don't trigger CI

### ISSUE THREAD

**Issue by gabsmprocha** [actions/stale#701]
## Your stale action configuration

```yml
jobs:
  stale:
    runs-on: ...
    steps:
      - uses: actions/stale@...
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'message'
          close-pr-message: 'message'
          days-before-pr-stale: 5
          days-before-pr-close: 1
          days-before-issue-stale: -1
          ignore-pr-updates: 'true'
          exempt-draft-pr: 'true'
          operations-per-run: 50
          remove-pr-stale-when-updated: 'false' 
```

I have a worfklow that runs only my stale action, and a separeted CI that is triggered whenever a pull request is closed, when the github actions bot closes some PR the CI is not being triggered even though it has the target events:

```
    pull_request:
        types: [opened, reopened, ready_for_review, edited, synchronize, closed]
        branches: [main]
```
Ps: if the same PR has been closed manually, the CI works fine
