### ISSUE TITLE
Feature Request - Tag the creator of the pull request

### ISSUE THREAD

**Issue by vikas027** [actions/stale#714]
## The problem
It would be great to have a way (optional) to tag the user who has created the PR in the `stale-pr-message` and `close-pr-message`.

## The solution
Maybe  a variable ` tag-requestor` can be used like this
```yaml
      - uses: actions/stale
        with:
          stale-pr-message: <some_msg>
          close-pr-message: <some_msg>
          tag-requestor: true
```
