### ISSUE TITLE
How to ignore any PR update

### ISSUE THREAD

**Issue by gabsmprocha** [actions/stale#716]
## Your stale action configuration

```yml
jobs:
  stale:
    runs-on: ...
    steps:
      - uses: actions/stale@v4
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'message'
          close-pr-message: 'message'
          days-before-pr-stale: 5
          days-before-pr-close: 1
          ignore-pr-updates: true
          exempt-draft-pr: true
          operations-per-run: 50
          remove-pr-stale-when-updated: false
```

## Further context

But always when there are comments or updates the pr is unable to close, I would like to close it regardless of any activity
_**Stale pull request is not old enough to close yet (hasComments? true, hasUpdate? true)**_

I thought the ignore-pr-updates parameter would do this, but it doesn't seem to be working as expected )=
