### ISSUE TITLE
Can comments be synced with changes to idle days?

### ISSUE THREAD

**Issue by shink** [actions/stale#732]
## Describe your issue

Hi, I just wonder can comments be synced with changes to idle days?
I modified them but the comments didn't sync.

Specifically, at the beginning, `days-before-issue-stale` was set to `30` and `days-before-issue-close` was set to `5`. The bot commented on the following message. But then I modified `days-before-issue-stale` to `60` and `days-before-issue-close` to `30`. Comments were not synced.

![image](https://user-images.githubusercontent.com/49934421/167775277-989edd45-cf56-4f34-98cc-2fffee7a32b4.png)

## Your stale action configuration

```yml
jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Mark issues and PRs
        uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 30 days with no activity.'
          days-before-issue-stale: 60       # the idle number of days before marking the issues as stale
          days-before-pr-stale: 60          # the idle number of days before marking the pull requests as stale
          days-before-issue-close: 30       # the idle number of days before closing the stale issues
          days-before-pr-close: 30          # the idle number of days before closing the stale pull requests
          operations-per-run: 500           # max number of operations per run
          exempt-issue-labels: 'WIP'        # labels on issues exempted from stale
          exempt-pr-labels: 'WIP'           # labels on PRs exempted from stale
          stale-issue-label: 'stale'        # label to apply on staled issues
          stale-pr-label: 'stale'           # label to apply on staled PRs
```
