### ISSUE TITLE
Stale label gets removed when manually added

### ISSUE THREAD

**Issue by hasezoey** [actions/stale#766]
## Describe your issue

Currently the `stale` label gets removed again when manually added because of `The issue is no longer stale. Removing the stale label...`

## Your stale action configuration

```yml
jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues  
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Marking Issue as stale, will be closed in 7 days if no more activity is seen'
          close-issue-message: 'Closing Issue because it is marked as stale'
          stale-issue-label: 'stale'
          exempt-issue-labels: help wanted,docs,enhancement,feature,parity,discussion,roadmap,bug,breaking,dependencies
          days-before-stale: 30
          days-before-close: 7
          remove-stale-when-updated: true
          enable-statistics: true
```

## Further context

If i have understood the PR #352 correctly, it should have fixed #188 by prioritizing a manually added `stale` label and not remove it again because of the manual add being counted as activity

Current Issue i am trying to set as stale: https://github.com/typegoose/typegoose/issues/499
Current action run with debug enabled: https://github.com/typegoose/typegoose/runs/7060586708
Current Stale action workflow (full file): https://github.com/typegoose/typegoose/blob/b8f4da34e7ccb90108285b97dd99b25b60b48ab0/.github/workflows/stale.yml

Action run Output:
```txt
::group::[#499] Issue #499
[#499] Issue #499
  [#499] Found this issue last updated at: 2022-06-26T11:57:43Z
  [#499] The option only-labels (​[https://github.com/actions/stale#only-labels​)](https://github.com/actions/stale#only-labels%E2%80%8B)) was not specified
  [#499]└── Continuing the process for this issue
  [#499] Days before issue stale: 30
  [#499] The issue is not closed nor locked. Trying to remove the close label...
  [#499]├── The close-issue-label (​[https://github.com/actions/stale#close-issue-label​)](https://github.com/actions/stale#close-issue-label%E2%80%8B)) option was not set
  [#499]└── Skipping the removal of the close label
  [#499] This issue has a stale label
  [#499] An exempt label was added after the stale label.
  [#499] The issue is no longer stale. Removing the stale label...
  [#499] Removing the label "stale" from this issue...
  [#499] The label "stale" was removed
  [#499] Skipping this issue because it has an exempt label
  [#499]1 operation consumed for this issue
  ::endgroup::
```
