### ISSUE TITLE
Date of last update reported by action not same as seen in PR

### ISSUE THREAD

**Issue by prasanthpul** [actions/stale#767]
## Your stale action configuration

```yml
jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 365
        days-before-close: 21
```

## Further context

Example PR: https://github.com/onnx/onnx/pull/2160 which was last updated on July 11, 2019

The output (https://github.com/onnx/onnx/runs/7052222196?check_suite_focus=true) says  

[#2160] Pull request #2160
  [#2160] Found this pull request last updated at: 2022-01-09T02:18:44Z
  [#2160] The option only-labels (​[https://github.com/actions/stale#only-labels​)](https://github.com/actions/stale#only-labels%E2%80%8B)) was not specified
  [#2160]└── Continuing the process for this pull request
  [#2160] Days before pull request stale: 365
  [#2160] The pull request is not closed nor locked. Trying to remove the close label...
  [#2160]├── The close-pr-label (​[https://github.com/actions/stale#close-pr-label​)](https://github.com/actions/stale#close-pr-label%E2%80%8B)) option was not set
  [#2160]└── Skipping the removal of the close label
  [#2160] This pull request hasn't a stale label
  [#2160] The option any-of-labels (​[https://github.com/actions/stale#any-of-labels​)](https://github.com/actions/stale#any-of-labels%E2%80%8B)) was not specified
  [#2160]└── Continuing the process for this pull request
  [#2160] This pull request has no milestone
  [#2160]└── Skip the milestones checks
  [#2160] This pull request has no assignee
  [#2160]└── Skip the assignees checks
  [#2160] This pull request is not stale
  [#2160] The option ignore-updates (​[https://github.com/actions/stale#ignore-updates​)](https://github.com/actions/stale#ignore-updates%E2%80%8B)) is disabled. The stale counter will take into account updates and comments on this pull request to avoid to stale when there is some update
  [#2160] This pull request should not be stale based on the last update date the 09-01-2022 (2022-01-09T02:18:44Z)
