### ISSUE TITLE
Action keep removing stale label and adding stale label

### ISSUE THREAD

**Issue by a631807682** [actions/stale#774]
## Describe your issue

For the last 3 hours, I keep getting notifications from actions/stale, it seems to keep checking its own comments This seems to be an issue with the new release, are there any changes I need to sync into the config?

## Your stale action configuration

```yml
name: "Close Missing Playground issues"
on:
  schedule:
  - cron: "*/10 * * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "The issue has been automatically marked as stale as it missing playground pull request link, which is important to help others understand your issue effectively and make sure the issue hasn't been fixed on latest master, checkout [https://github.com/go-gorm/playground](https://github.com/go-gorm/playground) for details. it will be closed in 30 days if no further activity occurs. if you are asking question, please use the `Question` template, most likely your question already answered https://github.com/go-gorm/gorm/issues or described in the document https://gorm.io ✨ [Search Before Asking](https://stackoverflow.com/help/how-to-ask) ✨"
        stale-issue-label: "status:stale"
        days-before-stale: 0
        days-before-close: 30
        remove-stale-when-updated: true
        only-labels: "type:missing reproduction steps"
```
## Further context

[issue](https://github.com/go-gorm/gorm/issues/5446#issuecomment-1185664932)
[action log](https://github.com/go-gorm/gorm/runs/7361330617?check_suite_focus=true)
