### ISSUE TITLE
"ignore-updates: true" still consumes operations pulling comments and events

### ISSUE THREAD

**Issue by austinpray-mixpanel** [actions/stale#779]
## Describe your issue

I have about 125 remaining PRs that are candidates to be closed as stale with my configuration. I have operations-per-run set to 100 and ignore-updates set to true. I expected this to not consume actions fetching events and comments for PRs and only consume actions closing PRs based on close date. Instead: I see it using actions fetching comments and events and only closing one PR at a time. I would have expected it to bypass fetching comments and events all together when ignore-updates is set to true.

```
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to theoperations-per-run (​[https://github.com/actions/stale#operations-per-run​)](https://github.com/actions/stale#operations-per-run%E2%80%8B))option which is currently set to100
Statistics:
Processed PRs: 635
New stale PRs: 1
Added PRs labels: 1
Added PRs comments: 1
Fetched items: 700
Fetched items events: 46
Fetched items comments: 46
Operations performed: 101
```

## Your stale action configuration

```yml
jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # TODO: slowly make this more aggressive
        # Rough idea is: 4y -> (Ask for feedback) -> 2y -> 1y -> ?
        days-before-stale: 730 # 2 years
        days-before-close: 7
        stale-pr-message: >
          This PR has been inactive 2+ years. It will be automatically closed in 7 days.
          Label this PR as "never-stale" to exempt it from this check.
        stale-pr-label: stale
        exempt-pr-labels: never-stale
        # TODO: eventually remove this, something happened where every PR was mass-updated in 2021
        # https://github.com/actions/stale#ignore-updates
        ignore-updates: true
        # See: https://github.com/actions/stale#operations-per-run
        # We have 15,000 api requests per hour on GitHub Enterprise and this runs during off-hours
        # See: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions
        operations-per-run: 100
```
