### ISSUE TITLE
Add an option to skip adding a comment while marking issue / pr as stale

### ISSUE THREAD

**Issue by mollyIV** [actions/stale#78]
### Description 

Currently there's no option for **not adding** a comment while marking an issue or a pull request as stale. As a real life example use case, a bot on [`fastlane`](https://github.com/fastlane/fastlane) repository only adds a label [`status: needs-attention`](https://github.com/fastlane/fastlane/labels/status%3A%20needs-attention) to the pull requests that have been hanging without any action for a while. It's a handy way to express the need for an action to be taken without an explicitly pinging a given person. 

### Proposal

I'd like to propose adding two parameters to the action's inteface:

```yaml
skip-stale-pr-message:
  description: 'Skip adding stale message when marking a pull request as stale.'
  default: false

skip-stale-issue-message:
  description: 'Skip adding stale message when marking an issue as stale.'
  default: false
```

No breaking changes, only opt-in. 

Empty `stale-pr-message` / `stale-issue-message` will always take a precedence over  `skip-stale-pr-message` / `skip-stale-issue-message`.

### Workaround 

Create a custom GitHub Action based on an official `stale` action implementation. 

I'll gladly implement this feature if a proposal is accepted 😊
