### ISSUE TITLE
`only-labels` generates a warning

### ISSUE THREAD

**Issue by prakhar1989** [actions/stale#82]
Hi,

I'm trying to use this github action to auto-close issues for a specific label that have had no activity in the last N days.

Here's how my configuration looks like 

```
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: 'waiting-for-response'
        stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Remove label or comment or this will be closed in 2 days'
        days-before-stale: 14
        days-before-close: 2
```

However, it generates a warning:

```
Unexpected input 'only-labels', valid inputs are ['repo-token', 'stale-issue-message', 'stale-pr-message', 'days-before-stale', 'days-before-close', 'stale-issue-label', 'exempt-issue-label', 'stale-pr-label', 'exempt-pr-label', 'operations-per-run']
```

As per [the code](https://github.com/actions/stale/blob/master/src/main.ts#L31) it seems `only-labels` is a valid option. What am I missing?
