### ISSUE TITLE
Stale action counts its own labeling/comment as activity

### ISSUE THREAD

**Issue by Pandapip1** [actions/stale#825]
## Describe your issue

This action detects its own comment/addition of a label as activity.

## Your stale action configuration

```yml
name: Mark stale PRs & Issues

on:
  schedule:
  - cron: 0 0 * * *  # Runs at 00:00 UTC every day.

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    name: Mark Stale Issues
    steps:
    - uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
      with:
        # General
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ascending: true # Since we have so many issues, the stale bot finds it hard to keep track. This makes sure that at least the oldest are removed.
        # Issue config
        stale-issue-message: There has been no activity on this issue for 1 week. It will be closed after 3 months of inactivity.
        close-issue-message: This issue was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback.
        days-before-issue-stale: 7
        days-before-issue-close: 49 # 49 + 7 weeks = 3 months
        exempt-issue-labels: discussions-to
        stale-issue-label: w-stale
        # PR config
        stale-pr-message: There has been no activity on this pull request for 2 weeks. It will be closed after 3 months of inactivity. If you would like to move this PR forward, please respond to any outstanding feedback or add a comment indicating that you have addressed all required feedback and are ready for a review.
        close-pr-message: This pull request was closed due to inactivity. If you are still pursuing it, feel free to reopen it and respond to any feedback or request a review in a comment.
        days-before-pr-stale: 14
        days-before-pr-close: 42 # 42 + 14 weeks = 3 months
        stale-pr-label: w-stale
```

## Further context

https://github.com/ethereum/EIPs/pull/5320#issuecomment-1244738910, https://github.com/ethereum/EIPs/actions/runs/3049288899/jobs/4915204689#step:2:732

```
[#5320] Pull request #5320
  [#5320] Found this pull request last updated at: 2022-09-13T00:23:57Z
  [#5320] The option only-labels (​[https://github.com/actions/stale#only-labels​)](https://github.com/actions/stale#only-labels%E2%80%8B)) was not specified
  [#5320] └── Continuing the process for this pull request
  [#5320] Days before pull request stale: 14
  [#5320] The pull request is not closed nor locked. Trying to remove the close label...
  [#5320] ├── The close-pr-label (​[https://github.com/actions/stale#close-pr-label​)](https://github.com/actions/stale#close-pr-label%E2%80%8B)) option was not set
  [#5320] └── Skipping the removal of the close label
  [#5320] This pull request has a stale label
  [#5320] The option any-of-labels (​[https://github.com/actions/stale#any-of-labels​)](https://github.com/actions/stale#any-of-labels%E2%80%8B)) was not specified
  [#5320] └── Continuing the process for this pull request
  [#5320] This pull request has no milestone
  [#5320] └── Skip the milestones checks
  [#5320] This pull request has no assignee
  [#5320] └── Skip the assignees checks
  [#5320] This pull request is already stale
  [#5320] Checking for label on this pull request
  [#5320] Pull request marked stale on: 2022-09-13T00:23:57Z
  [#5320] Checking for comments on pull request since: 2022-09-13T00:23:57Z
  [#5320] Comments that are not the stale comment or another bot: 0
  [#5320] Pull request has been commented on: false
  [#5320] Days before pull request close: 42
  [#5320] Pull request has been updated: true
  [#5320] The option remove-stale-when-updated (​[https://github.com/actions/stale#remove-stale-when-updated​)](https://github.com/actions/stale#remove-stale-when-updated%E2%80%8B)) is: true
  [#5320] The stale label should not be removed
  [#5320] Remove the stale label since the pull request has been updated and the workflow should remove the stale label when updated
  [#5320] The pull request is no longer stale. Removing the stale label...
  [#5320] Removing the label "w-stale" from this pull request...
  [#5320] The label "w-stale" was removed
  [#5320] Skipping the process since the pull request is now un-stale
  [#5320] 3 operations consumed for this pull request
```
