### ISSUE TITLE
Stale bot takes some of its prior changes as activity that resets the stale clock

### ISSUE THREAD

**Issue by ghogen** [actions/stale#842]
## Describe your issue

We're looking at the newer activity of the bot and still seeing that the bot's own prior activity (adding comments, adding or removing labels) is still counted as activity on the issue. This is unrelated to the timestamp comparison problem, but it matches the original title of issue 795. I'm using "v5" which should pick up the 5.2.0 which I think should have the update. Here's an issue that we processed through the latest version and it decides that the "last updated date" is 9/15/2022 which is when it removed the stale label. The last real update was back in March.

![image](https://user-images.githubusercontent.com/1660093/194625265-ae55488f-c1c9-46fc-b48b-cf357d83868e.png)

https://github.com/MicrosoftDocs/visualstudio-docs/issues/6077
We have two other examples all with the same problem:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/6678 - bot takes its own update on 8/4 as last activity date. Last non-bot update was January, so it should be marked stale, but it is not due to the bot update on 8/4.

Expectation: any activity by the bot (comments, adding/removing labels, etc.) should not be counted as update activity that resets the stale clock.

## Your stale action configuration

```yml
name: close-stale-issues

on:
  schedule:
    - cron: "0 0 * * 4"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Thanks for sharing your feedback. We apologize for our delayed response. Due to the sheer volume of feedback in our repo, we have decided to prioritize the newest issues and are automatically closing our oldest issues with an Issues bot. If you believe your feedback is still actionable, then either respond directly in this issue or open a new documentation issue and we’ll review. If no activity occurs in the next 14 days, this issue will be closed.'
          close-issue-message: 'This issue is closed. If you feel this issue has been closed in error, please submit a new comment on the issue, and we will review it.'
          stale-issue-label: 'stale'
          close-issue-label: 'auto-close'
          exempt-issue-labels: 'exempt'
          remove-stale-when-updated: true
          days-before-close: 14
          days-before-issue-stale: 180
          days-before-pr-stale: -1
          operations-per-run: 500
```

## Further context

Related to #795
