### ISSUE TITLE
3.0.4 - Activity does not remove STALE flag

### ISSUE THREAD

**Issue by william76** [actions/stale#86]
I'm testing out 3.0.4 and it looks like putting in a comment or mentioning an issue that is marked STALE does not remove the flag.

I'm using a stale.yaml file that looks like this:
```yaml
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 1
        days-before-close: 1
        stale-issue-message: >
          Stale message goes here.
        operations-per-run: 25
        stale-pr-message: >
          Stale message goes here.
        stale-issue-label: 'STALE'
        stale-pr-label: 'STALE'
        exempt-issue-labels: 'WIP'
        exempt-pr-labels: 'WIP'
        remove-stale-when-updated: true
```

I created an issue that got marked stale this morning and I added a comment. Then re-ran the workflow and I see this in the output:
```
Found issue: issue #1 - Test Issue 1 last updated 2020-05-27T16:21:57Z (is pr? false)
Found a stale issue
Checking for label Stale on issue #1
Issue #1 marked stale on: 2020-05-27T16:21:57Z
Checking for comments on issue #1 since 2020-05-27T16:21:57Z
Comments not made by william76 or another bot: 0
Issue #1 has been commented on: false
Issue #1 has been updated: true
Stale issue is not old enough to close yet (hasComments? false, hasUpdate? true
```
It sees that the issue was updated, but it's not clearing the stale label. In the output I don't think the workflow is seeing the comment that I added after the issue was marked stale.

Adding a mention to a STALE issue from a PR or other issue also appears to not reset the flag.

The repository where I'm testing this is at https://github.com/william76/workflowTest/issues
