### ISSUE TITLE
Stale bot closing after incorrect interval

### ISSUE THREAD

**Issue by jwilner** [actions/stale#90]
Hi -- 

I wanted a slightly more complex workflow with the stale action that I thought would work, but doesn't appear to be.  I may have misconfigured it, but it's not clear to me how; I'm hoping someone can point me in the right direction.

My desired activity is:

1) Mark a PR stale after five days
2) Twenty-five days after that, mark it with another label, more threatening :)
3) Five days after that, close it. 

To achieve this, I actually configured two versions of the action on the repository as follows:

`.github/workflows/stale.yml`:
```yaml
name: Mark stale issues and pull requests
...
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "This issue has been automatically marked as stale because it has not had recent activity."
        stale-pr-label: "stale :bread:"
        days-before-stale: 3
        days-before-close: 999
        exempt-pr-labels: "On Hold :stop_sign:"
```

`.github/workflows/closer.yml`:
```yaml
name: Close stale issues and pull requests
...
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "This issue will be closed soon. Please mark it 'On Hold :stop_sign:' to skip."
        stale-pr-label: "WILL BE CLOSED :skull_and_crossbones:"
        days-before-stale: 25
        days-before-close: 5
        exempt-pr-labels: "On Hold :stop_sign:"
```

My expectation is that a stale PR would be marked stale on day five so its `updated_at` would bump up, 25 days later the other action would pick it up and mark it with the new label (so its `updated_at` would again bump up), and then five days later it would be closed. 

The first action goes as expected, and the marking of the second goes as expected -- but the closing event does not happen as expected. Here's an example log:

```
Found a stale pr
Checking for label WILL BE CLOSED :skull_and_crossbones: on issue #2318
Issue #2318 marked stale on: 2020-05-23T03:04:26Z
Checking for comments on issue #2318 since 2020-05-23T03:04:26Z
Comments not made by jwilner or another bot: 0
Issue #2318 has been commented on: false
Issue #2318 has been updated: true
Stale pr is not old enough to close yet (hasComments? false, hasUpdate? true
```

The PR was marked with `WILL BE CLOSED ☠️` on `2020-05-23T03:04:26Z`. Yet it's far more than five days since then and the PR has not been closed.

When I check the code here, the `updatedSince` logic instead seems to be waiting _30_ days after the last update: https://github.com/actions/stale/blob/master/src/IssueProcessor.ts#L204-L207. I would expect this check to only be passing `daysBeforeClose`, not `daysBeforeClose + daysBeforeStale`, since adding the stale label updates the `updatedAt`. 

Clearly though this must be working for other people, so I assume I've misconfigured something.

Any help would be greatly appreciated.
